"""Tests for codegen.pdf_ingest using a committed synthetic PDF.

The fixture ``tests/fixtures/synthetic.pdf`` is a 3-page PDF generated by
``tests/fixtures/make_synthetic_pdf.py`` with placeholder content shaped
like a Parsely page (large title, flavor body, cyan rule body, one
underlined noun per page). It exists so we can exercise PyMuPDF without
depending on the gitignored Parsely PDF.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("pymupdf")

from text_adventure_games.codegen.pdf_ingest import ingest_pdf

FIXTURE = Path(__file__).parent / "fixtures" / "synthetic.pdf"


def test_ingest_returns_one_page_per_input_page():
    pages = ingest_pdf(FIXTURE, (1, 4))
    assert len(pages) == 4
    assert [p.page_number for p in pages] == [1, 2, 3, 4]


def test_each_page_has_a_title_guess():
    pages = ingest_pdf(FIXTURE, (1, 3))
    titles = [p.title_guess for p in pages]
    assert "Cabin" in titles
    assert "Forest" in titles
    assert "Cliff" in titles


def test_flavor_and_rule_spans_are_separated_by_color():
    pages = ingest_pdf(FIXTURE, (1, 1))
    page = pages[0]
    flavor_text = page.flavor_text().lower()
    rule_text = page.rule_text().lower()
    # The flavor body lands on the flavor channel.
    assert "small cabin" in flavor_text
    # The rule body lands on the rule channel (not in flavor).
    assert "after being lit" in rule_text
    assert "after being lit" not in flavor_text


def test_underlined_nouns_are_attributed_to_the_underlined_span():
    pages = ingest_pdf(FIXTURE, (1, 3))
    # One underline per page in the fixture; the underlined noun should
    # appear in page.item_nouns.
    item_nouns_per_page = [tuple(p.item_nouns) for p in pages]
    assert any("lantern" in t for t in item_nouns_per_page)
    assert any("branch" in t for t in item_nouns_per_page)
    assert any("rope" in t for t in item_nouns_per_page)


def test_page_range_subset():
    pages = ingest_pdf(FIXTURE, (2, 2))
    assert len(pages) == 1
    assert pages[0].title_guess == "Forest"


def test_unknown_colors_are_classified_other():
    """Synthetic PDF only uses black + cyan; no spans should be 'other'
    except possibly the title (if its font/size puts it outside flavor)."""
    pages = ingest_pdf(FIXTURE, (1, 1))
    colors = {s.color for s in pages[0].spans}
    assert "flavor" in colors
    assert "rule" in colors


def test_partial_underline_credits_only_the_underlined_word():
    """When an underline sits beneath one word of a longer sentence, the
    ingest should credit that word (or the contiguous underlined phrase)
    -- NOT the whole sentence text. Page 4 of the fixture has only 'soda'
    underlined inside 'A can of soda drops out of the machine.'.
    """
    pages = ingest_pdf(FIXTURE, (4, 4))
    page = pages[0]
    # The underlined token should be 'soda' (one word), not 'A can of soda
    # drops out of the machine.' or any other whole-span credit.
    assert "soda" in [n.lower() for n in page.item_nouns]
    # And the over-greedy old behavior should be gone: no full-sentence
    # phrase should appear in the item_nouns.
    for n in page.item_nouns:
        assert "drops out" not in n.lower(), (
            f"item_nouns contains over-greedy credit {n!r}; " "should be just 'soda'"
        )
        assert (
            "can of" not in n.lower() or n.lower() == "soda"
        ), f"item_nouns contains over-greedy credit {n!r}"
