extends Node
## Headless smoke test for the campus scenes.
##
## Loads each content scene, lets it run a couple of frames so `_ready()` paints,
## then asserts its campus map actually drew tiles. Exits non-zero if any scene
## fails to load/instantiate or paints zero cells — so `run_smoke_test.sh` (or CI)
## catches a broken `.tmj` / tileset regen before it lands. The map files churn a
## lot (they're regenerated by the geo tools), and Godot only *warns* about a map
## it can't read; nothing fails the build. This turns that warning into a failure.
##
## It also gates the scene's ROOT script (issue #639): a parse/compile error in a
## root script (e.g. viewer.gd) doesn't stop the scene loading — the tiles are
## painted by the child tiled_map.gd, so the tile check alone still reported PASS
## while the viewer was broken. When a scene is flagged `root_script`, instantiate
## leaves `get_script() == null` if the root failed to compile, which we now fail on.
##
## It reads the TileMapLayer's used-cell data, not pixels, so it needs no GPU and
## runs under `--headless`. Run:
##   Godot --headless --path <project> res://scenes/smoke_test.tscn
## Exit code: 0 = every scene OK, 1 = at least one scene failed a check.

# The content scenes worth checking. Utility scenes (snapshot, smoke_test) are
# intentionally excluded. Add new gameplay/view scenes here as they're created.
# `root_script`: true if the scene's root node carries a script we want to gate
# against parse errors (campus_urban's root has none — only its children do —
# so it's false; viewer's root is viewer.gd, so it's true).
const SCENES := [
	{"path": "res://scenes/campus_urban.tscn", "root_script": false},
	{"path": "res://scenes/viewer.tscn", "root_script": true},
]


func _ready() -> void:
	var failures := 0
	for entry in SCENES:
		failures += await _check_scene(entry)
	# The landing menu (issue #399) builds its whole UI in code, so it has no tiles
	# to count — it gets its own check (does it paint any buttons?) rather than a
	# spot in SCENES, which would trip the tile-cells assertion.
	failures += await _check_menu()
	# The Past-runs browser (issue #716) is a code-built menu-like scene with no
	# campus tiles, so — like the landing menu — it gets its own check (root script
	# attached + it builds without a backend) rather than a spot in SCENES.
	failures += await _check_past_runs()
	# The Simulation Setup scene (issue #733) is another code-built menu-like
	# scene with no campus tiles, so -- like the menu and Past-runs -- it gets
	# its own check (root script attached + it builds without a backend).
	failures += await _check_simulation_setup()
	# The snapshot gallery (issue #253) is a code-built pop-up, not a scene in SCENES;
	# check that it builds and accepts snapshots (the capture path it feeds is GPU-only).
	failures += _check_gallery()
	var checks := SCENES.size() + 4
	if failures == 0:
		print("smoke_test: PASS — %d scene(s) OK" % checks)
	else:
		printerr("smoke_test: FAIL — %d of %d scene(s) had problems" % [failures, checks])
	get_tree().quit(1 if failures > 0 else 0)


# Returns 0 if the scene is healthy, 1 if it failed a check (the count of failures).
func _check_scene(entry: Dictionary) -> int:
	var path: String = entry["path"]
	var packed: PackedScene = load(path)
	if packed == null:
		printerr("  %s: could not load scene (missing file or broken script ref)" % path)
		return 1
	var inst: Node = packed.instantiate()
	if inst == null:
		printerr("  %s: could not instantiate scene" % path)
		return 1

	add_child(inst)
	# tiled_map.gd paints synchronously in `_ready()`, so a couple of idle frames is
	# plenty for the map to exist before we inspect it (no GPU/render wait needed).
	await get_tree().process_frame
	await get_tree().process_frame

	# A parse error in the root script leaves it unattached (get_script() == null)
	# while the scene still loads and paints — so the tile check below can't see it.
	if entry.get("root_script", false) and inst.get_script() == null:
		printerr("  %s: root script failed to load (parse/compile error?)" % path)
		inst.queue_free()
		await get_tree().process_frame
		return 1

	var cells := _count_tile_cells(inst)
	inst.queue_free()
	await get_tree().process_frame

	if cells <= 0:
		printerr("  %s: campus map painted 0 cells (broken .tmj or missing tileset?)" % path)
		return 1
	print("  %s: OK (%d map cells)" % [path, cells])
	return 0


# Sum the used cells across every TileMapLayer in the instance. tiled_map.gd makes
# the root `Map` node the ground layer and adds one child layer per `.tmj` layer,
# so we recurse rather than checking a single node.
func _count_tile_cells(node: Node) -> int:
	var total := 0
	if node is TileMapLayer:
		total += (node as TileMapLayer).get_used_cells().size()
	for child in node.get_children():
		total += _count_tile_cells(child)
	return total


# Returns 0 if the landing menu is healthy, 1 if it failed a check.
func _check_menu() -> int:
	var path := "res://scenes/main_menu.tscn"
	var packed: PackedScene = load(path)
	if packed == null:
		printerr("  %s: could not load scene (missing file or broken script ref)" % path)
		return 1
	var inst: Node = packed.instantiate()
	if inst == null:
		printerr("  %s: could not instantiate scene" % path)
		return 1

	add_child(inst)
	# main_menu.gd builds every Control in _ready(), which runs during add_child; a
	# couple of idle frames also lets the backdrop SubViewport settle.
	await get_tree().process_frame
	await get_tree().process_frame

	# The menu's root carries main_menu.gd; a parse error unattaches it (see #639).
	if inst.get_script() == null:
		printerr("  %s: root script failed to load (parse/compile error?)" % path)
		inst.queue_free()
		await get_tree().process_frame
		return 1

	var buttons := _count_buttons(inst)
	inst.queue_free()
	await get_tree().process_frame

	if buttons <= 0:
		printerr("  %s: menu painted 0 buttons (broken _ready?)" % path)
		return 1
	print("  %s: OK (%d menu button(s))" % [path, buttons])
	return 0


# Returns 0 if the Past-runs browser (issue #716) is healthy, 1 if not. With no
# backend URL set it renders the "connect first" state -- we only assert the root
# script attached (parse gate, #639) and that it built its buttons (Back + rows).
func _check_past_runs() -> int:
	var path := "res://scenes/past_runs.tscn"
	var packed: PackedScene = load(path)
	if packed == null:
		printerr("  %s: could not load scene (missing file or broken script ref)" % path)
		return 1
	var inst: Node = packed.instantiate()
	if inst == null:
		printerr("  %s: could not instantiate scene" % path)
		return 1
	add_child(inst)
	await get_tree().process_frame
	await get_tree().process_frame
	if inst.get_script() == null:
		printerr("  %s: root script failed to load (parse/compile error?)" % path)
		inst.queue_free()
		await get_tree().process_frame
		return 1
	var buttons := _count_buttons(inst)
	inst.queue_free()
	await get_tree().process_frame
	if buttons <= 0:
		printerr("  %s: built 0 buttons (broken _ready?)" % path)
		return 1
	print("  %s: OK (%d button(s))" % [path, buttons])
	return 0


# Returns 0 if the Simulation Setup browser (issue #733) is healthy, 1 if not.
# With no backend URL set it renders the "no backend" state -- we only assert
# the root script attached (parse gate, #639) and that it built its buttons
# (Start + Back).
func _check_simulation_setup() -> int:
	var path := "res://scenes/simulation_setup.tscn"
	var packed: PackedScene = load(path)
	if packed == null:
		printerr("  %s: could not load scene (missing file or broken script ref)" % path)
		return 1
	var inst: Node = packed.instantiate()
	if inst == null:
		printerr("  %s: could not instantiate scene" % path)
		return 1
	add_child(inst)
	await get_tree().process_frame
	await get_tree().process_frame
	if inst.get_script() == null:
		printerr("  %s: root script failed to load (parse/compile error?)" % path)
		inst.queue_free()
		await get_tree().process_frame
		return 1
	var buttons := _count_buttons(inst)
	inst.queue_free()
	await get_tree().process_frame
	if buttons <= 0:
		printerr("  %s: built 0 buttons (broken _ready?)" % path)
		return 1
	print("  %s: OK (%d button(s))" % [path, buttons])
	return 0


# Count the Button descendants of a node — the menu builds its choices in code, so
# zero buttons means _ready() bailed before laying the UI out.
func _count_buttons(node: Node) -> int:
	var total := 0
	if node is Button:
		total += 1
	for child in node.get_children():
		total += _count_buttons(child)
	return total


# Returns 0 if the snapshot gallery (issue #253) builds and takes snapshots, 1 if not.
# Pure UI — no GPU/render needed — so it runs headless like the rest of this test. It
# builds the pop-up (_ready), adds two dummy captures, and asserts the count plus that a
# clickable thumbnail (a TextureButton) was built for each. The actual pixel capture
# needs a real renderer and is covered by the manual viewer check, not here.
func _check_gallery() -> int:
	var gallery: Node = load("res://scripts/snapshot_gallery.gd").new()
	add_child(gallery)  # entering the tree runs _ready(), which builds the grid
	var dummy := ImageTexture.create_from_image(Image.create_empty(1, 1, false, Image.FORMAT_RGBA8))
	gallery.add_snapshot(dummy, "test time A")
	gallery.add_snapshot(dummy, "test time B")
	var n: int = gallery.count()
	var thumbs := _count_texture_buttons(gallery)
	gallery.queue_free()
	if n != 2 or thumbs != 2:
		printerr("  snapshot_gallery: expected 2 snapshots + 2 thumbnails, got %d + %d" % [n, thumbs])
		return 1
	print("  snapshot_gallery: OK (%d snapshots)" % n)
	return 0


# Thumbnails are TextureButtons (not plain Buttons), so _count_buttons misses them.
func _count_texture_buttons(node: Node) -> int:
	var total := 0
	if node is TextureButton:
		total += 1
	for child in node.get_children():
		total += _count_texture_buttons(child)
	return total
