extends TileMapLayer
## Paints the real UPenn campus, overlaid with Cute Fantasy tiles.
##
## The map is an OpenStreetMap-derived Tiled map (a `.tmj`) generated by the
## repo's geo tool (`tools/geo/osm_to_tiled.py`). A `.tmj` is just JSON: six tile
## layers whose `data` arrays hold one *category GID* per cell —
##   1 = ground, 2 = grass, 3 = water, 4 = path, 5 = road, 6 = building.
## We don't need a Tiled importer: we read the JSON ourselves, build a TileSet in
## code (the same trick as `ground.gd`), and translate each GID to a Cute Fantasy
## tile via `GID_TO_SOURCE`. The result is the actual street/building geometry of
## campus drawn as a textured top-down world instead of flat coloured cells.

@export_file("*.tmj") var map_path: String = "res://maps/upenn_core.tmj"

# Cute Fantasy textures, wired in the scene.
@export var grass_tile: Texture2D      # Tiles/Grass_Middle.png  (16x16 flat fill)
@export var path_tile: Texture2D       # Tiles/Path_Middle.png   (16x16 flat fill)
@export var water_tile: Texture2D      # Tiles/Water_Middle.png  (16x16 flat fill)
@export var building_sheet: Texture2D  # Outdoor decoration/House_1_Wood_Base_Blue.png

const TILE_PX := 16

# Atlas-source ids for the tile kinds we register in the TileSet below.
const GRASS := 0
const PATH := 1
const WATER := 2
const ROAD := 3
const BUILDING := 4

# A 16x16 patch of the house's blue shingle roof, used as the building footprint
# fill (the pack has no single-tile building, so we crop one from the house sheet
# — a 6x8 grid of 16px cells). Tweak if a cleaner roof cell is wanted.
const ROOF_ATLAS := Vector2i(3, 1)

# Cute Fantasy has no road tile, so vehicle roads reuse the dirt path tile,
# darkened so they read as distinct from the lighter pedestrian paths.
const ROAD_TINT := Color(0.55, 0.55, 0.62)

# Our .tmj category GID -> the TileSet source that draws it.
const GID_TO_SOURCE := {
	1: GRASS,     # ground (base carpet)
	2: GRASS,     # grass / parks / landuse
	3: WATER,     # water
	4: PATH,      # footways (Locust Walk)
	5: ROAD,      # vehicle roads
	6: BUILDING,  # building footprints
}


func _ready() -> void:
	tile_set = _build_tile_set()
	var tmj := _load_tmj()
	if not tmj.is_empty():
		_paint(tmj)


func _load_tmj() -> Dictionary:
	# Read the .tmj as plain text so Godot's resource importer never touches it.
	var f := FileAccess.open(map_path, FileAccess.READ)
	if f == null:
		push_error("campus_map: cannot open %s" % map_path)
		return {}
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("campus_map: %s is not valid Tiled JSON" % map_path)
		return {}
	return parsed


func _build_tile_set() -> TileSet:
	var ts := TileSet.new()
	ts.tile_size = Vector2i(TILE_PX, TILE_PX)
	_add_fill(ts, GRASS, grass_tile)
	_add_fill(ts, PATH, path_tile)
	_add_fill(ts, WATER, water_tile)
	_add_fill(ts, ROAD, path_tile, ROAD_TINT)
	_add_patch(ts, BUILDING, building_sheet, ROOF_ATLAS)
	return ts


# A single 16x16 tile from the top-left of a flat fill texture, optionally tinted.
func _add_fill(ts: TileSet, id: int, tex: Texture2D, tint := Color.WHITE) -> void:
	var src := TileSetAtlasSource.new()
	src.texture = tex
	src.texture_region_size = Vector2i(TILE_PX, TILE_PX)
	src.create_tile(Vector2i.ZERO)
	if tint != Color.WHITE:
		src.get_tile_data(Vector2i.ZERO, 0).modulate = tint
	ts.add_source(src, id)


# A single 16x16 patch cropped from a larger sheet at the given atlas cell.
func _add_patch(ts: TileSet, id: int, tex: Texture2D, cell: Vector2i) -> void:
	var src := TileSetAtlasSource.new()
	src.texture = tex
	src.texture_region_size = Vector2i(TILE_PX, TILE_PX)
	src.create_tile(cell)
	ts.add_source(src, id)


func _paint(tmj: Dictionary) -> void:
	var w := int(tmj.get("width", 0))
	if w == 0:
		push_error("campus_map: map width is 0")
		return
	# Which atlas cell each source draws (fills use the origin; buildings the roof).
	var atlas_of := {
		GRASS: Vector2i.ZERO, PATH: Vector2i.ZERO, WATER: Vector2i.ZERO,
		ROAD: Vector2i.ZERO, BUILDING: ROOF_ATLAS,
	}
	# Layers are listed bottom-to-top; painting in order lets later layers
	# (buildings) overwrite earlier ones (the path beneath them) at a cell.
	for layer in tmj.get("layers", []):
		if layer.get("type", "") != "tilelayer":
			continue
		var data: Array = layer.get("data", [])
		var painted := 0
		for i in data.size():
			var gid := int(data[i])
			if gid == 0 or not GID_TO_SOURCE.has(gid):
				continue
			var src_id: int = GID_TO_SOURCE[gid]
			set_cell(Vector2i(i % w, i / w), src_id, atlas_of[src_id])
			painted += 1
		print("campus_map: layer %-9s painted %d cells" % [layer.get("name", "?"), painted])
