extends Node
## Headless smoke test for the campus scenes.
##
## Loads each content scene, lets it run a couple of frames so `_ready()` paints,
## then asserts its campus map actually drew tiles. Exits non-zero if any scene
## fails to load/instantiate or paints zero cells — so `run_smoke_test.sh` (or CI)
## catches a broken `.tmj` / tileset regen before it lands. The map files churn a
## lot (they're regenerated by the geo tools), and Godot only *warns* about a map
## it can't read; nothing fails the build. This turns that warning into a failure.
##
## It reads the TileMapLayer's used-cell data, not pixels, so it needs no GPU and
## runs under `--headless`. Run:
##   Godot --headless --path <project> res://scenes/smoke_test.tscn
## Exit code: 0 = every scene OK, 1 = at least one scene failed a check.

# The content scenes worth checking. Utility scenes (snapshot, smoke_test) are
# intentionally excluded. Add new gameplay/view scenes here as they're created.
const SCENES := [
	"res://scenes/campus_urban.tscn",
	"res://scenes/penn_replay.tscn",
]


func _ready() -> void:
	var failures := 0
	for path in SCENES:
		failures += await _check_scene(path)
	if failures == 0:
		print("smoke_test: PASS — %d scene(s) OK" % SCENES.size())
	else:
		printerr("smoke_test: FAIL — %d of %d scene(s) had problems" % [failures, SCENES.size()])
	get_tree().quit(1 if failures > 0 else 0)


# Returns 0 if the scene is healthy, 1 if it failed a check (the count of failures).
func _check_scene(path: String) -> int:
	var packed: PackedScene = load(path)
	if packed == null:
		printerr("  %s: could not load scene (missing file or broken script ref)" % path)
		return 1
	var inst: Node = packed.instantiate()
	if inst == null:
		printerr("  %s: could not instantiate scene" % path)
		return 1

	add_child(inst)
	# tiled_map.gd paints synchronously in `_ready()`, so a couple of idle frames is
	# plenty for the map to exist before we inspect it (no GPU/render wait needed).
	await get_tree().process_frame
	await get_tree().process_frame

	var cells := _count_tile_cells(inst)
	inst.queue_free()
	await get_tree().process_frame

	if cells <= 0:
		printerr("  %s: campus map painted 0 cells (broken .tmj or missing tileset?)" % path)
		return 1
	print("  %s: OK (%d map cells)" % [path, cells])
	return 0


# Sum the used cells across every TileMapLayer in the instance. tiled_map.gd makes
# the root `Map` node the ground layer and adds one child layer per `.tmj` layer,
# so we recurse rather than checking a single node.
func _count_tile_cells(node: Node) -> int:
	var total := 0
	if node is TileMapLayer:
		total += (node as TileMapLayer).get_used_cells().size()
	for child in node.get_children():
		total += _count_tile_cells(child)
	return total
